### ISSUE TITLE
ContestPoolCreated event in factory needs to publish the amountPerPlayer field

### ISSUE THREAD

**Issue by dmolina79** [Bitbrackets/bitbrackets_smart_contracts#12]
We need the event  to also have the amountPerPlayer, all constructor fields should be checked for other events to be sure we are exposing the data we need to the events.

Example in the Factory:
emit ContestPoolCreated(address(this), definition.contestName, manager, newContestPoolAddress, _name, _amountPerPlayer );

**Comment by salazarguille** [comment]
The field amountPerPlayer was added in ContestPoolCreated event.
